"""
Enums for product-related types and categories.
"""
from enum import Enum

class LicenseType(str, Enum):
    """License types for products and technologies."""
    MIT = "MIT"
    APACHE_2_0 = "Apache-2.0"
    GPL_3_0 = "GPL-3.0"
    BSD_2_CLAUSE = "BSD-2-Clause"
    BSD_3_CLAUSE = "BSD-3-Clause"
    MPL_2_0 = "MPL-2.0"
    LGPL_3_0 = "LGPL-3.0"
    EPL_2_0 = "EPL-2.0"
    UNLICENSE = "Unlicense"
    PROPRIETARY = "Proprietary"

class ProductCategory(str, Enum):
    """Categories for products and services."""
    CREDITS = "credits"
    WORKFLOWS = "workflows"
    ESSENTIALS = "essentials"
    SOFTWARE = "software"
    HARDWARE = "hardware"
    SERVICE = "service"
    SUBSCRIPTION = "subscription"
    DIGITAL_DOWNLOAD = "digital_download"
    PHYSICAL_GOOD = "physical_good"
    COURSE = "course"
    TEMPLATE = "template"
    PLUGIN = "plugin"
    THEME = "theme"
    CONSULTING = "consulting"
    SUPPORT = "support"
    MAINTENANCE = "maintenance"
    CUSTOM_DEVELOPMENT = "custom_development"
    TRAINING = "training"
    CONTENT_CREATION = "content_creation"
    MARKETING = "marketing"
    DESIGN = "design"
    OTHER = "other"
